function electric_synapse_adaptive!(du,u,h,p,t)
    # parameter
    C, g_L, V_rest,V_th, d_es, τ_f, τ_l, u_f, g_0, g_max, a, σ, c = p
    
    # if spiked, reset
    if u[1]>0
        u[1]=V_rest
    end
    if u[2]>0
        u[2]=V_rest
    end
    
    # dynamical equation
    
    ΔT=2
    # time diff btw two adjacent spikes generated by the two neurons
    # ΔT should be computed from history potential
    I_ext=0.8*exp(-t/a)+σ*(sqrt(1-c)*randn())
    I_ext1=sqrt(c)*randn()
    I_ext2=sqrt(c)*randn()
    du[1]=1/C*(-g_L*(u[1]-V_rest)+u[3]*(h(p,t-d_es)[2]-u[1])+I_ext+I_ext1)
    du[2]=1/C*(-g_L*(u[2]-V_rest)+u[3]*(h(p,t-d_es)[1]-u[2])+I_ext+I_ext2)
    du[3]=1/τ_f*(-(u[3]-g_0)+u_f*(g_max-u[3])*exp(-abs(ΔT)/τ_l))
    # u[3] is g_es

    # if above threshold, then spike
    if u[1]>V_th
        u[1]=30
    end
    if u[2]>V_th
        u[2]=30
    end
    
end